title: Ph.D. Student
author: Roger Bai
email: rogerbai92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You can find links to my resume and talks here.

# social links
github_username:  roger-bai # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
